version: "3"
services:
  db:  # Mettez 'db' au lieu de 'database'
    container_name: API_Symfony_Commands
    image: mysql:8.0
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: API_Symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./var/dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: API_PhpMyAdmin_Commands
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - '8080:80'

volumes:
  dbdata: